apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abohmeed/argocdplugin-terraform-lab.git'
    targetRevision: HEAD
    path: 'manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true