apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-configuration
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abohmeed/argocdplugin-terraform-lab.git'
    targetRevision: HEAD
    path: 'configurations'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true