apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
type: Opaque
data:
  username: YWhtZWQ=  # Base64 encoded value of 'ahmed'
  password: bXlwYXNzd29yZA==  # Base64 encoded value of 'mypassword'